
services:
  api:
    build:
      context: .
      dockerfile: Dockerfile.api
    ports:
      - "8000:8000"
    environment:
      - AWS_DEFAULT_REGION=ap-southeast-2
      - FRACTAL_SERVICE_URL=n11608676-autoscale-assesment3-785201285.ap-southeast-2.elb.amazonaws.com
    working_dir: /app